version: '3'
services:
  app:
    container_name: the-forum-backend-api
    build: .
    depends_on:
      - postgres
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_DIALECT: ${DB_DIALECT}
      DB_OPERATOR_ALIASES: ${DB_OPERATOR_ALIASES}
      DB_SSL: ${DB_SSL}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - ${PORT}:${PORT}
    command: yarn run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    container_name: the-forum-backend-database
    image: postgres:10.4
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # DB_USERNAME: ${DB_USERNAME}
      # DB_PASSWORD: ${DB_PASSWORD}
      # DB_NAME: ${DB_NAME}
      # DB_HOST: ${DB_HOST}
      # DB_PORT: ${DB_PORT}
      # DB_DIALECT: ${DB_DIALECT}
      # DB_OPERATOR_ALIASES: ${DB_OPERATOR_ALIASES}
      # DB_SSL: ${DB_SSL}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
